apiVersion: apps/v1
kind: Deploymnet
metadata:
  name: guestbook
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLales:
      app: guestbook
  template:
    metada:
      labels:
        app: guestbook
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook
        ports:
        - containerport: 80
